services:
  db:
    image: mariadb
    env_file: ./.env
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: lazardb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

  api:
    depends_on:
      - db
    build: ./lazar-backend-api
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://db:3306/lazardb",
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASS",
        "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
